logging:
  level:
    root: ERROR
    com.tdcr.dockerize: DEBUG
  file: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

application:
  message: Hey there! message from
  appname: DockerWorld