logging:
  level:
    root: ERROR
    com.tdcr.dockerize: DEBUG
  file: logs/dockerworld.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

application:
  message: Hey there!
  appname: I'm theDarkCoderRises from DockerWorld.

server.port: 8081

dockerDaemonMap:
   LOCAL_DD: "localhost"
   AWS_DD: "13.232.246.215"
